# Docker Compose override for development
# This file is automatically loaded by docker-compose and provides development-specific configurations

version: '3.8'

services:
  frontend:
    # Enable development mode with hot reload
    build:
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HMR_PORT=5174
    command: npm run dev
    ports:
      - "5173:5173"  # Vite dev server
      - "5174:5174"  # HMR port

  backend:
    # Enable development mode for Sanity Studio
    build:
      target: builder
    volumes:
      - ./resonance:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3333:3333"

  # Disable nginx in development (use Vite dev server directly)
  nginx:
    profiles:
      - production
