version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - resonance-network
    depends_on:
      - backend
    restart: unless-stopped

  # Backend service (Sanity Studio)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    networks:
      - resonance-network
    restart: unless-stopped

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - resonance-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  resonance-network:
    driver: bridge

volumes:
  ssl-certs:
    driver: local
