[dev]
  command = "vite"
  port = 5173
  targetPort = 5174

# Traditional build command for Netlify (Docker not available in Netlify build environment)
[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  
# Docker-based build for GitHub Actions CI/CD
# The Docker pipeline runs in GitHub Actions and deploys via netlify-cli
# [build]
#   command = "./deploy.sh build && ./deploy.sh netlify"
#   publish = "netlify-deploy"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "https://tvi7xjbr.sanity.studio/*"
  status = 301

[[redirects]]
  from = "/admin"
  to = "https://tvi7xjbr.sanity.studio"
  status = 301

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Security headers for all routes
[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Permissions-Policy = "camera=(), microphone=(), geolocation=()"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.sanity.io https://*.supabase.co; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"

[[headers]]
  for = "/admin/*"
    [headers.values]
      X-Frame-Options = "SAMEORIGIN"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
